id = "zapphire-theme"
name = "Zapphire"
version = "0.0.1"
schema_version = 1
authors = ["dryrunner"]
description = "A lightweight Sapphire-inspired theme for Zed."
repository = "https://github.com/dryrunner/zapphire"
